# Workflow to deploy release to s3

name: Release Workflow

# Controls when the workflow will run
on:
  release:
    types:
      - published
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Run Deployment
    runs-on: ubuntu-latest
  
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
    CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Upload site to S3
      run: ./scripts/upload.sh

    - name: Invalidate CloudFront Distribution
      run: ./scripts/invalidate.sh